stages:
  stage_01:
    cmd: python stage-01.py
    deps: 
      - stage-01.py
    outs:
      - artifacts.txt
  stage_02:
    cmd: python stage-02.py
    deps: 
      - artifacts.txt
      - stage-02.py
   